services:
  amd64-runner:
    profiles:
      - amd64
    build:
      dockerfile: Dockerfile
    extends:
      file: .reusable-runner.yml
      service: runner

  arm64-runner:
    profiles:
      - arm64
    build:
      dockerfile: Dockerfile.mac
    platform: linux/arm64
    extends:
      file: .reusable-runner.yml
      service: runner
